const {chromium}=require('playwright');const fs=require('fs');
(async()=>{
const browser=await chromium.launch({channel:'msedge',headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000}});const page=await context.newPage();
await page.goto('https://foundersarena.exoasia.org/sign-in');await page.locator('input[type=email]').fill(process.env.QA_EMAIL);await page.locator('input[type=password]').fill(process.env.QA_PASSWORD);await page.locator('button[type=submit]').click();await page.waitForURL('**/dashboard',{timeout:45000});
await context.route('**/*',async route=>{if(['POST','PUT','PATCH','DELETE'].includes(route.request().method())){console.log('BLOCKED_WRITE '+route.request().url().replace(/\?.*/,'')+' '+route.request().postData());await route.fulfill({status:400,contentType:'application/json',body:JSON.stringify({message:'QA intercepted; no production write performed'})});}else await route.continue();});
const out=[];
async function capture(label){const row={label,url:page.url(),text:await page.locator('body').innerText(),buttons:await page.locator('button').allTextContents(),inputs:await page.locator('input').evaluateAll(es=>es.map(e=>({type:e.type,placeholder:e.placeholder}))),links:await page.locator('a[href]').evaluateAll(es=>es.map(e=>({text:e.innerText,href:e.getAttribute('href')})))};out.push(row);fs.writeFileSync('scratch/live-qa/deep-results.json',JSON.stringify(out,null,2));await page.screenshot({path:'scratch/live-qa/evidence/deep-'+label+'.png',fullPage:true});console.log(JSON.stringify(row));}
const net=[];page.on('response',async r=>{if(r.url().includes('/api/'))net.push({url:r.url().replace(/\?.*/,''),status:r.status()});});page.on('requestfailed',r=>console.log('FAILED '+r.url().replace(/\?.*/,'')+' '+r.failure()?.errorText));
await page.goto('https://foundersarena.exoasia.org/matches');await page.waitForTimeout(20000);await capture('matches-20s');console.log('MATCHNET '+JSON.stringify(net));
for(const p of ['/projects/4fcec300-045f-45df-a157-0e004f3c5d41','/data-room/4fcec300-045f-45df-a157-0e004f3c5d41','/profile/complete','/payments/success','/startup/complete-profile']){await page.goto('https://foundersarena.exoasia.org'+p);await page.waitForTimeout(4000);await capture(p.replace(/\//g,'_'));}
await page.goto('https://foundersarena.exoasia.org/documents');await page.waitForTimeout(2000);await page.route('**/rest/v1/member_documents*',async route=>{if(route.request().method()==='POST'){console.log('BLOCKED_DOCUMENT_WRITE '+route.request().postData());await route.fulfill({status:400,contentType:'application/json',body:JSON.stringify({message:'QA intercepted; no production write performed'})});}else await route.continue();});
page.on('dialog',async d=>{console.log('DIALOG '+d.message());await d.dismiss();});await page.getByRole('button',{name:'Submit sec-certificate',exact:true}).click();await page.waitForTimeout(1000);await capture('documents-intercepted');
const anonymous=await browser.newContext();const response=await anonymous.request.post('https://foundersarena.exoasia.org/api/auth/check-email',{data:{email:process.env.QA_EMAIL}});console.log('EMAIL_CHECK_KNOWN '+response.status()+' '+await response.text());const missing=await anonymous.request.post('https://foundersarena.exoasia.org/api/auth/check-email',{data:{email:'qa-nonexistent-20261003@example.invalid'}});console.log('EMAIL_CHECK_MISSING '+missing.status()+' '+await missing.text());await anonymous.close();
await browser.close();
})().catch(e=>{console.error(e.message);process.exit(1)});
