const {chromium}=require('playwright');const fs=require('fs');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});const context=await browser.newContext();const page=await context.newPage();const rows=[];
page.on('pageerror',e=>console.log('PAGEERROR '+e.message));
await page.goto('https://foundersarena.exoasia.org/sign-in');await page.locator('input[type=email]').fill(process.env.QA_EMAIL);await page.locator('input[type=password]').fill(process.env.QA_PASSWORD);await page.locator('button[type=submit]').click();await page.waitForURL('**/dashboard',{timeout:45000});
await context.route('**/*',async route=>{if(['POST','PUT','PATCH','DELETE'].includes(route.request().method()))await route.fulfill({status:400,contentType:'application/json',body:'{"error":"QA intercepted"}'});else await route.continue();});
const id='4fcec300-045f-45df-a157-0e004f3c5d41';
for(const path of ['/data-room/'+id,'/data-room/'+id+'?tab=pitch','/data-room/'+id+'?tab=snapshot','/onboarding','/projects/new','/accept-nomination']){await page.goto('https://foundersarena.exoasia.org'+path);await page.waitForTimeout(7000);const row={path,url:page.url(),text:await page.locator('body').innerText()};rows.push(row);console.log(JSON.stringify(row));await page.screenshot({path:'scratch/live-qa/evidence/final'+path.replace(/[^a-z0-9-]/gi,'_')+'.png',fullPage:true});}
for(const [path,button] of [['/stage-1','Activate Stage 01 ->'],['/stage-2','Submit documents ->'],['/stage-3','Select pathway']]){const logs=[];const listen=m=>logs.push(m.text());page.on('console',listen);await page.goto('https://foundersarena.exoasia.org'+path);await page.getByRole('button',{name:button,exact:true}).first().click();await page.waitForTimeout(1000);rows.push({path,after:page.url(),logs});console.log('STAGE '+JSON.stringify(rows.at(-1)));page.off('console',listen);}
fs.writeFileSync('scratch/live-qa/final-results.json',JSON.stringify(rows,null,2));await browser.close();})().catch(e=>{console.error(e.message);process.exit(1)});
