const {chromium}=require('playwright');const fs=require('fs');
(async()=>{const browser=await chromium.launch({channel:'msedge',headless:true});const context=await browser.newContext();const page=await context.newPage();const rows=[];fs.mkdirSync('scratch/live-qa/evidence',{recursive:true});
async function capture(label){const row={label,url:page.url(),text:await page.locator('body').innerText(),links:await page.locator('a[href]').evaluateAll(es=>es.map(e=>({text:e.innerText,href:e.getAttribute('href')}))),inputs:await page.locator('input').evaluateAll(es=>es.map(e=>({type:e.type,placeholder:e.placeholder}))),overflow:await page.evaluate(()=>({viewport:innerWidth,width:document.documentElement.scrollWidth}))};rows.push(row);fs.writeFileSync('scratch/live-qa/ui-results.json',JSON.stringify(rows,null,2));await page.screenshot({path:'scratch/live-qa/evidence/ui-'+label+'.png',fullPage:true});console.log(JSON.stringify({label,url:row.url,text:row.text.slice(-3000),overflow:row.overflow}));}
for(const p of ['/','/sign-up','/get-invited','/reset-password','/accept-invite','/accept-nomination','/not-authorized','/docs']){await page.goto('https://foundersarena.exoasia.org'+p);await page.waitForTimeout(1200);await capture('public'+p.replace(/\//g,'_'));}
await page.goto('https://foundersarena.exoasia.org/sign-in');await page.locator('input[type=email]').fill(process.env.QA_EMAIL);await page.locator('input[type=password]').fill(process.env.QA_PASSWORD);await page.locator('button[type=submit]').click();await page.waitForURL('**/dashboard',{timeout:45000});
await context.route('**/*',async route=>{if(['POST','PUT','PATCH','DELETE'].includes(route.request().method())){await route.fulfill({status:400,contentType:'application/json',body:JSON.stringify({error:'QA intercepted; no production write performed'})});}else await route.continue();});
for(const [path,button] of [['/community','Threads'],['/feature-requests','+ New Request'],['/payments','Request custom top-up'],['/account-settings','Report a bug']]){await page.goto('https://foundersarena.exoasia.org'+path);await page.waitForTimeout(3500);await page.getByRole('button',{name:button,exact:true}).click();await page.waitForTimeout(2000);await capture('modal'+path.replace(/\//g,'_'));}
await page.goto('https://foundersarena.exoasia.org/stage-4');const logs=[];page.on('console',msg=>logs.push(msg.text()));const before=page.url();await page.getByRole('button',{name:'Back to Stage 3',exact:true}).click();await page.waitForTimeout(1000);await page.getByRole('button',{name:'Open',exact:true}).first().click();await page.waitForTimeout(1000);await capture('stage4-noop');console.log('STAGE4 '+JSON.stringify({before,after:page.url(),logs}));
await context.close();const anon=await browser.newContext({viewport:{width:390,height:600}});const small=await anon.newPage();for(const p of ['/sign-in','/sign-up']){await small.goto('https://foundersarena.exoasia.org'+p);await small.waitForTimeout(800);console.log('SMALL '+p+' '+JSON.stringify(await small.locator('button[type=submit]').evaluateAll(es=>es.map(e=>({text:e.innerText,rect:e.getBoundingClientRect().toJSON(),height:innerHeight,bodyHeight:document.documentElement.scrollHeight})))));await small.screenshot({path:'scratch/live-qa/evidence/small'+p.replace(/\//g,'_')+'.png',fullPage:true});}await browser.close();})().catch(e=>{console.error(e.message);process.exit(1)});
